"""
routes_fir.py – FIR management endpoints including AI-powered complaint parsing.

Endpoints:
  POST /api/v1/fir/parse    – Gemini-powered NLP extraction from raw complaint text
  POST /api/v1/fir/         – Generate a blockchain FIR document
  GET  /api/v1/fir/{fir_id}/download – Download a generated FIR PDF
"""
from __future__ import annotations

import json
import logging
from uuid import UUID

from fastapi import APIRouter, HTTPException, status
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field

from app.core.config import get_settings
from app.models.schemas import FIRCreate, FIRResponse

log      = logging.getLogger(__name__)
settings = get_settings()

router = APIRouter(prefix="/fir", tags=["FIR"])


# ── Gemini request / response models ─────────────────────────────────────────

class ComplaintParseRequest(BaseModel):
    """Raw complaint narrative submitted for AI-powered structured extraction."""
    complaintText: str | None = Field(default=None, description="Unstructured police complaint narrative text")
    complaint_text: str | None = Field(default=None, description="Snake_case alias for complaint text")

    @property
    def text(self) -> str:
        return (self.complaintText or self.complaint_text or "").strip()


class ParsedComplaintResponse(BaseModel):
    """
    Structured fields extracted by Gemini from the complaint narrative.
    All fields are Optional — the LLM may not be able to extract every value.
    """
    suspect_wallet_address: str | None = Field(
        default=None,
        description="On-chain wallet address of the suspect",
    )
    blockchain_type: str | None = Field(
        default=None,
        description="Detected blockchain ('tron', 'solana', 'ethereum', or null)",
    )
    max_trace_hops: int | None = Field(
        default=None,
        ge=1,
        le=10,
        description="Suggested maximum trace depth (1–10) based on complaint complexity",
    )
    estimated_loss_inr: float | None = Field(
        default=None,
        description="Estimated financial loss in INR extracted from the narrative",
    )
    summary: str | None = Field(
        default=None,
        description="One-sentence summary of the complaint generated by the model",
    )
    confidence: str | None = Field(
        default=None,
        description="Model's self-assessed confidence: 'high', 'medium', or 'low'",
    )
    raw_model_output: str | None = Field(
        default=None,
        description="Raw JSON string returned by Gemini (for debugging)",
    )


# ── Gemini extraction prompt ──────────────────────────────────────────────────

_EXTRACTION_PROMPT = """You are a blockchain forensics expert and legal analyst assistant for Indian law enforcement.

A police officer has submitted the following complaint narrative. Your job is to extract key investigative parameters from the text.

COMPLAINT TEXT:
\"\"\"
{complaint_text}
\"\"\"

Extract the following fields and return ONLY a valid JSON object — no markdown, no explanation, just raw JSON:

{{
  "suspect_wallet_address": "<blockchain address if mentioned, else null>",
  "blockchain_type": "<one of: tron, solana, ethereum — based on address format or context; else null>",
  "max_trace_hops": <integer 1-10 based on transaction chain complexity described; use 5 if unclear>,
  "estimated_loss_inr": <numeric INR amount if mentioned, else null>,
  "summary": "<one concise sentence summarising the complaint>",
  "confidence": "<high|medium|low based on how much structured data was present in the complaint>"
}}

Rules:
- TRON addresses start with 'T' and are 34 characters long (Base58).
- Ethereum/EVM addresses start with '0x' and are 42 characters long.
- Solana addresses are 32-44 Base58 characters with no '0x' prefix.
- If the blockchain type cannot be determined from the address, infer from context keywords (e.g., 'TRC-20', 'USDT on TRON', 'MetaMask', 'Phantom').
- For max_trace_hops: use 3 for simple single-hop fraud, 5 for multi-layer layering, 7-10 for complex mixing/tumbler cases.
- Return null for any field you cannot extract with reasonable confidence.
- Do NOT hallucinate addresses or amounts not present in the text.
"""


# ── AI parse endpoint ─────────────────────────────────────────────────────────

@router.post(
    "/parse",
    response_model=ParsedComplaintResponse,
    status_code=status.HTTP_200_OK,
    summary="AI-powered complaint parser (Gemini)",
    description=(
        "Accepts a raw complaint narrative and uses the Google Gemini API to extract "
        "the suspect wallet address, blockchain type, maximum trace hops, estimated loss, "
        "and a one-sentence summary. Returns a structured JSON response."
    ),
)
async def parse_complaint(payload: ComplaintParseRequest) -> ParsedComplaintResponse:
    """
    Extract structured investigative parameters from a raw FIR/complaint narrative
    using the Google Gemini API (google-genai SDK).

    Steps:
      1. Build a structured extraction prompt with the complaint text.
      2. Call Gemini with JSON output mode (response_mime_type = application/json).
      3. Parse and validate the returned JSON.
      4. Return a ParsedComplaintResponse.
    """
    if not payload.text or len(payload.text) < 5:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="Complaint narrative text must be at least 5 characters long.",
        )

    if not settings.GEMINI_API_KEY:
        log.warning("GEMINI_API_KEY not set — cannot parse complaint text")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="GEMINI_API_KEY is not configured. Set it in the .env file.",
        )

    # ── Call Gemini API ───────────────────────────────────────────────────────
    try:
        from google import genai
        from google.genai import types as genai_types

        client = genai.Client(api_key=settings.GEMINI_API_KEY)
        prompt = _EXTRACTION_PROMPT.format(complaint_text=payload.text)

        target_model = settings.GEMINI_MODEL or "gemini-3.6-flash"
        gen_config = genai_types.GenerateContentConfig(
            response_mime_type="application/json",
            temperature=0.1,
            max_output_tokens=2048,
            thinking_config=genai_types.ThinkingConfig(thinking_budget=0),
        )
        try:
            response = client.models.generate_content(
                model=target_model,
                contents=prompt,
                config=gen_config,
            )
        except Exception as model_err:
            log.warning("Gemini model '%s' failed (%s); falling back to 'gemini-3.6-flash'", target_model, model_err)
            response = client.models.generate_content(
                model="gemini-3.6-flash",
                contents=prompt,
                config=gen_config,
            )

        raw_text = (response.text or "").strip()
        log.debug("Gemini raw output: %s", raw_text)

    except ImportError as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="google-genai SDK not installed. Run: pip install google-genai",
        ) from exc
    except Exception as exc:
        log.error("Gemini API call failed: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Gemini API error: {exc}",
        )

    # ── Parse Gemini JSON response ────────────────────────────────────────────
    try:
        extracted: dict = json.loads(raw_text)
    except json.JSONDecodeError as exc:
        log.error("Gemini returned invalid JSON: %s | raw=%s", exc, raw_text)
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"Gemini returned non-JSON output: {raw_text[:300]}",
        )

    # ── Validate max_trace_hops bounds ────────────────────────────────────────
    hops = extracted.get("max_trace_hops")
    if hops is not None:
        hops = max(1, min(10, int(hops)))

    # ── Build response ────────────────────────────────────────────────────────
    return ParsedComplaintResponse(
        suspect_wallet_address = extracted.get("suspect_wallet_address"),
        blockchain_type        = extracted.get("blockchain_type"),
        max_trace_hops         = hops,
        estimated_loss_inr     = extracted.get("estimated_loss_inr"),
        summary                = extracted.get("summary"),
        confidence             = extracted.get("confidence"),
        raw_model_output       = raw_text,
    )


# ── FIR generation endpoint ───────────────────────────────────────────────────

@router.post(
    "/",
    response_model=FIRResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Generate a blockchain FIR document",
)
async def generate_fir(payload: FIRCreate) -> FIRResponse:
    """
    Produce a legally formatted FIR PDF for a given case,
    embedding transaction trails and risk evidence.
    """
    # TODO: wire up legal.pdf_generator + evidence_cert
    raise HTTPException(
        status_code=status.HTTP_501_NOT_IMPLEMENTED,
        detail="FIR PDF generation not yet implemented.",
    )


@router.get(
    "/{fir_id}/download",
    summary="Download a generated FIR PDF",
    response_class=FileResponse,
)
async def download_fir(fir_id: UUID) -> FileResponse:
    """Stream the PDF file for a previously generated FIR."""
    # TODO: fetch PDF path from DB and stream
    raise HTTPException(
        status_code=status.HTTP_501_NOT_IMPLEMENTED,
        detail="FIR PDF download not yet implemented.",
    )
