"""
privacy_tracer.py – Privacy Coin (Monero XMR / Zcash ZEC) & Swapper Interception Engine.

Addresses the law-enforcement challenge of tracing privacy-focused cryptocurrencies.
Since Monero (XMR) utilizes ring signatures, stealth addresses, and RingCT on-chain,
direct mathematical graph traversal across the Monero network is obscured.

Investigative Strategy:
  1. Off-Chain Swapper Deposit Interception:
     Criminals launder USDT/BTC into XMR via Instant No-KYC Swappers (FixedFloat,
     ChangeNOW, SideShift.ai, SimpleSwap). We detect and isolate the deposit hop.
  2. Temporal & Value Fingerprinting:
     Calculates exact deposit timestamp T_0, value, and expected output currency.
  3. Automated Section 94 BNSS / International Subpoena Dossier:
     Generates a targeted legal compulsion questionnaire directed to swapper compliance
     desks demanding the Monero transaction key (tx_key), stealth output address,
     and access IP/device telemetry.
"""
from __future__ import annotations

import logging
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from typing import Any

from app.models.schemas import TransferEdge, WalletNode
from app.vasp.registry import get_vasp_by_hot_wallet, is_no_kyc_swapper

log = logging.getLogger(__name__)


@dataclass
class SwapperInterceptRecord:
    """Record of funds entering an instant swapper for privacy coin conversion."""
    swapper_name: str
    swapper_address: str
    deposit_tx_hash: str
    deposit_value: float
    deposit_token: str
    timestamp: str
    compliance_email: str
    target_privacy_asset: str  # "Monero (XMR)" or "Zcash (ZEC)"
    subpoena_questionnaire: list[str]


@dataclass
class PrivacyCoinDossier:
    """Full investigative dossier for privacy coin off-ramping in a case."""
    case_id: str
    suspect_address: str
    detected_swapper_hops: list[SwapperInterceptRecord]
    total_privacy_diverted_usd: float
    investigative_playbook: list[str]
    statutory_legal_basis: str
    generated_at: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


_DEFAULT_SUBPOENA_QUESTIONS = [
    "1. Provide the complete outbound transaction hash (tx_hash) and 256-bit Transaction Private Key (tx_key) for the Monero/Zcash transfer generated by this order.",
    "2. Provide the destination stealth address / subaddress where the privacy coins were disbursed.",
    "3. Furnish all HTTP access logs including originating IPv4/IPv6 address, source port, timestamp, browser user-agent header, and device fingerprint associated with the order creation.",
    "4. State the user's provided refund address (e.g. USDT/BTC return address) and any email address or chat identifier entered during order placement.",
    "5. Furnish transaction logs for all orders in your database sharing the same IP address, device fingerprint, or refund wallet.",
]


def generate_privacy_coin_dossier(
    case_id: str,
    suspect_address: str,
    nodes: list[WalletNode],
    edges: list[TransferEdge],
) -> PrivacyCoinDossier:
    """
    Generate an authenticated Privacy Coin Swapper Interception Dossier for a case.
    """
    intercepts: list[SwapperInterceptRecord] = []
    total_diverted = 0.0

    for edge in edges:
        target_addr = edge.to_address
        if is_no_kyc_swapper(target_addr):
            entry = get_vasp_by_hot_wallet(target_addr)
            swapper_name = entry.name if entry else "Instant No-KYC Swapper"
            email = entry.nodal_officer_email if entry else "compliance@fixedfloat.com"

            intercept = SwapperInterceptRecord(
                swapper_name=swapper_name,
                swapper_address=target_addr,
                deposit_tx_hash=edge.tx_hash,
                deposit_value=edge.value,
                deposit_token=edge.token,
                timestamp=edge.timestamp.isoformat(),
                compliance_email=email,
                target_privacy_asset="Monero (XMR) / Privacy Pool",
                subpoena_questionnaire=_DEFAULT_SUBPOENA_QUESTIONS,
            )
            intercepts.append(intercept)
            total_diverted += edge.value

    # If no swapper hop was explicitly triggered, create investigative guidance
    playbook = [
        "1. Swapper Interception: Serve Section 94 BNSS notice to the compliance email listed in each intercept record within 24 hours.",
        "2. Monero Tx_Key Verification: Once the swapper provides the 256-bit tx_key and destination address, use the Monero CLI (`monero-wallet-cli --check-tx-key`) to cryptographically prove that the funds arrived in the suspect's stealth wallet.",
        "3. Exchange Off-Ramp Corroboration: Monitor Indian and global exchanges (Binance, CoinDCX, Kraken) for matching value deposits occurring 2 to 48 hours post-swap.",
        "4. IP Geolocation & ISP Notice: Subpoena the ISP associated with the order placement IP address under Section 91 CrPC / Section 94 BNSS.",
    ]

    legal_basis = (
        "Section 94 Bharatiya Nagarik Suraksha Sanhita (BNSS) 2023 r/w Section 69B Information Technology Act 2000. "
        "Instant swappers providing services to Indian residents fall under PMLA reporting obligations as Virtual Asset Service Providers (VASPs)."
    )

    return PrivacyCoinDossier(
        case_id=case_id,
        suspect_address=suspect_address,
        detected_swapper_hops=intercepts,
        total_privacy_diverted_usd=total_diverted,
        investigative_playbook=playbook,
        statutory_legal_basis=legal_basis,
        generated_at=datetime.now(UTC).isoformat(),
    )
